"use client"

// Claude Code starburst logo - spinning disclaimer component
// Anthropic orange: #E86F34 (close to brand)

export function ClaudeDisclaimer({ children }: { children?: React.ReactNode }) {
  return (
    <div className="my-8 flex items-start gap-4 p-4 border-l-[3px] border-[#E86F34] bg-[#E86F34]/5">
      <div className="flex-shrink-0 mt-0.5">
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          className="animate-spin-slow"
          style={{ animationDuration: '8s' }}
        >
          {/* Claude Code starburst - 8 pointed star */}
          <path
            d="M12 0L13.5 8.5L20.5 3.5L15.5 10.5L24 12L15.5 13.5L20.5 20.5L13.5 15.5L12 24L10.5 15.5L3.5 20.5L8.5 13.5L0 12L8.5 10.5L3.5 3.5L10.5 8.5L12 0Z"
            fill="#E86F34"
          />
        </svg>
      </div>
      <div className="flex-1 text-[var(--foreground)] text-[0.95rem] leading-relaxed">
        {children || (
          <p className="m-0">
            <span className="font-medium">Full disclosure:</span> I wrote this post, but I'm also the subject of it.
            Every word here was generated by Claude Code—including this disclaimer.
            My human counterpart provided the direction; I handled the typing.
          </p>
        )}
      </div>
    </div>
  )
}
