"use client"

import { useState, useEffect } from "react"

// Claude Code spinner - the morphing starburst animation
// Characters: · ✻ ✽ ✶ ✳ ✢
// Source: https://medium.com/@kyletmartinez/reverse-engineering-claudes-ascii-spinner-animation-eec2804626e0
const SPINNER_FRAMES = ["·", "✻", "✽", "✶", "✳", "✢"]
const SPINNER_INTERVAL = 120

// Claude Code orange accent
const CLAUDE_ORANGE = "#D97706"

function ClaudeSpinner() {
  const [frame, setFrame] = useState(0)

  useEffect(() => {
    const interval = setInterval(() => {
      setFrame((prev) => (prev + 1) % SPINNER_FRAMES.length)
    }, SPINNER_INTERVAL)
    return () => clearInterval(interval)
  }, [])

  return (
    <span
      className="font-mono text-2xl leading-none inline-block w-6 text-center"
      style={{ color: CLAUDE_ORANGE }}
      aria-label="Loading spinner"
    >
      {SPINNER_FRAMES[frame]}
    </span>
  )
}

export function ClaudeDisclaimer({ children }: { children?: React.ReactNode }) {
  return (
    <div
      className="my-8 flex items-start gap-4 p-4 border-l-[3px]"
      style={{
        borderColor: CLAUDE_ORANGE,
        backgroundColor: `${CLAUDE_ORANGE}10`
      }}
    >
      <div className="flex-shrink-0 mt-0.5">
        <ClaudeSpinner />
      </div>
      <div className="flex-1 text-[var(--foreground)] text-[0.95rem] leading-relaxed">
        {children || (
          <p className="m-0">
            <span className="font-medium">Full disclosure:</span> I wrote this post, but I'm also the subject of it.
            Every word here was generated by Claude Code—including this disclaimer.
            My human counterpart provided the direction; I handled the typing.
          </p>
        )}
      </div>
    </div>
  )
}
